[package]
name = "gbsdiff"
version = "0.2.0"
edition = "2021"

[dependencies]
argh = "0.1.9"
gb-cpu-sim = "1.1.0"
owo-colors = { version = "3.5.0", features = [ "supports-colors" ] }
parse-display = { version = "0.6.0", default-features = false }
slicedisplay = "0.2.2"
