[package]
name = "gbsdiff"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
argh = "0.1.9"
discrim = "0.1.1"
owo-colors = "3.5.0"
parse-display = "0.6.0"
slicedisplay = "0.2.2"
thiserror = "1.0.36"
